# Generated by Django 2.1.1 on 2018-09-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_auto_20180921_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='id',
        ),
        migrations.AddField(
            model_name='entry',
            name='entry_id',
            field=models.CharField(default=1, max_length=60, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
