# Generated by Django 2.1.1 on 2018-09-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20180921_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_id',
            field=models.IntegerField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
