# Generated by Django 2.1.1 on 2018-09-21 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_auto_20180921_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
